<?php 

/**
 * @file
 * Implementation of Units module API for volume units.
 */

/**
 * Implementation of hook_define_units()
 * 
 */

function generate_length_unit($short_name, $full_name, $symbol) {
  return array(
    'category_id' => 'length',
    'category' => t('Length units'),
    'shortname' => $short_name,
    'fullname' => $full_name,
    'symbol' => $symbol,
    'decimals' => 2,
  );  
}

function length_units_define_units() {
  return array(
    'length_mm' => generate_length_unit(t('mm'), t('Millimeter'), t('mm')),
    'length_cm' => generate_length_unit(t('cm'), t('Centimeter'), t('cm')),
    'length_dm' => generate_length_unit(t('dm'), t('Decimeter'), t('dm')),
    'length_m' => generate_length_unit(t('m'), t('Meter'), t('m')),
    'length_km' => generate_length_unit(t('km'), t('Kilometer'), t('km')),
  );
}
