<?php 

/**
 * @file
 * Implementation of Units module API for volume units.
 */

/**
 * Implementation of hook_define_units()
 * 
 */

function generate_length_unit($short_name, $full_name, $symbol) {
  return array(
    'category_id' => 'length',
    'category' => t('Length units'),
    'shortname' => $short_name,
    'fullname' => $full_name,
    'symbol' => $symbol,
    'decimals' => 2,
  );  
}

function length_units_define_units() {
  return array(
    'length_mm' => generate_length_unit('mm', 'Millimeter', 'mm'),
    'length_cm' => generate_length_unit('cm', 'Centimeter', 'cm'),
    'length_dm' => generate_length_unit('dm', 'Decimeter', 'dm'),
    'length_m' => generate_length_unit('m', 'Meter', 'm'),
    'length_km' => generate_length_unit('km', 'Kilometer', 'km'),
  );
}
