<?php 

/**
 * @file
 * Implementation of Units module API for volume units.
 */

/**
 * Implementation of hook_define_units()
 * 
 */

function generate_volume_unit($short_name, $full_name, $symbol) {
  return array(
    'category_id' => 'volume',
    'category' => t('Volume units'),
    'shortname' => $short_name,
    'fullname' => $full_name,
    'symbol' => $symbol,
    'decimals' => 2,
  );  
}

function volume_units_define_units() {
  return array(
    'volume_ml' => generate_volume_unit(t('ml'), t('Milliliter'), t('ml')),
    'volume_l' => generate_volume_unit(t('liter'), t('Liter'), t('l')),
    'volume_cm3' => generate_volume_unit(t('kub.cm'), t('Cubic centimeter'), t('cc')),
    'volume_dm3' => generate_volume_unit(t('kub.dm.'), 'Cubic decimeter', t('cdm')),
    'volume_m3' => generate_volume_unit(t('kub.m.'), t('Cubic meter'), t('cbm')),
  );
}
